Formula1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_race_home(request):
    return redirect("track_list")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("race.urls")),
    path("", redirect_to_race_home),
]

race/urls.py
from django.urls import path
from race.views import track_list, track_detail, driver_list, upcoming_races

urlpatterns = [
    path("races/", track_list, name="track_list"),
    path("upcoming/", upcoming_races, name="upcoming_races"),
    path("races/<int:id>/", track_detail, name="track_detail"),
    path("drivers/", driver_list, name= "driver_list")
]

accounts/models.py
from django.db import models

# Create your models here.

race/models.py
from django.db import models
from datetime import date
# Create your models here.


class Track(models.Model):
    name = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    url = models.URLField()
    date = models.DateField(null=True)

    def __str__(self):
        return self.name
    @property
    def has_passed(self):
        return self.date < date.today()


class Team(models.Model):
    name = models.CharField(max_length=250)
    country = models.CharField(max_length=250)
    team_principle = models.CharField(max_length=250)
    place_in_championship = models.SmallIntegerField(null = True, blank = True)

    def __str__(self):
        return self.name


class Driver(models.Model):
    name = models.CharField(max_length=250)
    country = models.CharField(max_length=250)
    team = models.ForeignKey(
        Team,
        related_name = "drivers_team",
        on_delete = models.CASCADE
    )
    races = models.ManyToManyField(
        Track, 
        through="Race"
        )

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name
    

class Race(models.Model):
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
    grid = models.IntegerField()
    date = models.DateField()
    # comments = models.ManyToManyField(Comment, blank=True)

    @property
    def has_passed(self):
        return self.date < date.today()

    class Meta:
        ordering = ["date"]

    def result(self):
        return f"{self.driver.name} grid {self.grid}"

    def __str__(self):
        return self.track.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

race/views.py
from django.shortcuts import render, get_object_or_404
from race.models import Race, Track, Driver
from datetime import date

# Create your views here.
def race_list(request):
    all_races = Race.objects.all()
    context = {
        "all_races" : all_races,
    }
    return render(request, "races/races.html", context)

def upcoming_races(request):
    all_races = Track.objects.all()
    upcoming_races = [race for race in all_races if not race.has_passed]
    context = {
        "upcoming_races": upcoming_races,
    }
    return render(request, "races/upcoming_races.html", context)

def race_detail(request, name):
    race_details = get_object_or_404(Race, track__name=name)
    context = {
        "race_details": race_details
    }
    return render(request, "races/details.html", context)


def track_list(request):
    all_tracks = Track.objects.all()
    context= {
        "all_tracks" : all_tracks,
    }
    return render(request, "races/tracks.html", context)


def track_detail(request, id):
    track_details = Track.objects.get(id=id)
    context = {
        "track_details": track_details,
    }
    return render(request, "races/details.html", context)

def driver_list(request):
    all_drivers = Driver.objects.select_related('team').order_by('team__place_in_championship', 'name')
    context = {
        "all_drivers" : all_drivers,
    }
    return render(request, "drivers/drivers.html", context)

race/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <div>
            Welcome to the Grid!
        </div>
        <nav>
            <div class="nav-links">
                <div id="logo">F1 FAN</div>
                <a class="link" href="{% url 'track_list' %}">2023 Race Schedule</a>
                <a class="link" href="{% url 'upcoming_races' %}">Upcoming Races!</a>
            </div>
            <div class="nav-triangle"> </div>
        </nav>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'race.css' %}">
    </head>
    <body>
        <div class="f1-border--top-right f1-border-color--carbonBlack">
        {% block content %}
        {% endblock content %}
    </div>
    </body>
</html>

race/templates/drivers/drivers.html
{% extends 'base.html' %}

{% block title %} List of Drivers {% endblock title %}
{% block content %}
<main>
    <h1>List of Drivers</h1>
    <div class="border">
    <div class="race_detail">
        {% regroup all_drivers by team as team_drivers %}
        {% for team in team_drivers %}
            <div class="team">
                <h2>Team: {{ team.grouper }}</h2>
                    {% for driver in team.list %}
                        <div>
                            <strong>Driver Name:</strong> {{ driver.name }}<br>
                            <strong>Country:</strong> {{ driver.country }}
                        </div>
                    {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
</main>
{% endblock content %}

race/templates/races/details.html
{% extends 'base.html' %}

{% block title %} {{track_details.name}} {% endblock title %}
{% block content %}
<main>
    <div>
        <h1> {{track_details.name}} </h1>
        {% if track_details.name == "Emilia Romagna Grand Prix" %}
        <div class="race_detail">
            This race has been postponed and cancelled
        </div>
        {% else %}
        <div class="race_detail_border">
        <div class="race_detail">
            <div class="race_detail_1">
                <div> Location: {{track_details.location}}</div>
                <div>Date: {{track_details.date}}</div>
                {% if track_details.has_passed == True %}
                <div class="passed"> Race has passed </div>
                {% endif %}
            </div>
                
            <div class="race_detail_2">
            <div class="race_results">
                <h2>Race Results</h2>
                <table class="results">
                    <tr>
                        <th>Position</th>
                        <th>Driver</th>
                    </tr>
                    {% if not track_details.race_set.all %}
                        </table>
                        <div> No results are currently available</div>
                    {% else %}
                    {% for race in track_details.race_set.all %}
                        <tr>
                            {% if race.grid == 0 %}
                            <td> DNF</td>
                            {% else %}
                            <td>{{ race.grid }}</td>
                            {% endif %}
                            
                            <td>{{ race.driver.name }}</td>
                        </tr>
                    {% endfor %}
                    {% endif %}
                </table>
            </div>
            
            <div id= "track-img"> 
                <div><h2>Track</h2></div><br>
            <img class="track" src = "{{track_details.url}}"> </div>
            <div>{{track_details.comment}}</div>
        </div>
    </div>
</div>
    {% endif %}
    </div>
</main>
{% endblock content %}

race/templates/races/tracks.html
{% extends 'base.html' %}

{% block title %} 2023 Races {% endblock title %}
{% block content %}
<main>
    
        <h1> 2023 Races </h1>
        <div class="border">
        <div class="tracks">
            {% for track in all_tracks %}
            <a href="{%url 'track_detail' track.id %}" class="race-link">
                <div class="track_info">
                    <h2>  {{track.name}} </h2>
                    <div class="small-info"> {{track.location}}</div>
                    <div class="small-info">{{track.date}}</div>
                </div>
            </a>
            {% endfor %}
    </div>
</div>
</main>
{% endblock content %}

race/templates/races/upcoming_races.html
{% extends 'base.html' %}

{% block title %} 2023 Races {% endblock title %}
{% block content %}
<main>
    
        <h1> Upcoming Races </h1>
        <div class="border">
        <div class="tracks">
            {% for race in upcoming_races %}
            <a href="{%url 'track_detail' race.id %}" class="race-link">
                <div class="track_info">
                    <h2>  {{race.name}} </h2>
                    <div class="small-info"> {{race.location}}</div>
                    <div class="small-info">{{race.date}}</div>
                </div>
            </a>
            {% endfor %}
    </div>
</div>
</main>
{% endblock content %}